FROM wordpress

MAINTAINER Fanus Inst.


# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug
# Install Less for WP-CLI
RUN apt-get update && apt-get -y install less curl
# Install WP-CLI
RUN curl -s -o /usr/local/bin/wp \
    https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp

RUN mkdir /var/www/html/wordpress
COPY ./wordpress /var/www/html/wordpress

WORKDIR /var/www/html
